-- ============================================================
-- Prime Access Ghana — Phase 2: Product Transfer Requests
-- Inter-warehouse stock movement, no approval step.
-- Flow: request -> (source ships physically) -> destination receives
--       Receive atomically moves stock source -> destination.
-- Safe to re-run. Run in Supabase SQL editor as one piece.
-- ============================================================

-- 1) TABLE -----------------------------------------------------
create table if not exists public.product_transfer_requests ( id uuid primary key default gen_random_uuid(), code text unique not null, product_id uuid references public.products(id) on delete set null, item_no text, description text, from_warehouse_id uuid references public.warehouses(id) on delete set null, from_branch_id uuid references public.branches(id) on delete set null, to_warehouse_id uuid references public.warehouses(id) on delete set null, to_branch_id uuid references public.branches(id) on delete set null, qty_requested int not null check (qty_requested > 0), qty_received int, payment_method text check (payment_method in ('cash','momo','pos','bank')), payment_provider text, payment_confirmed boolean default false, delivery_type text check (delivery_type in ('internal','external')), requested_by uuid references public.staff(id) on delete set null, requested_by_code text, received_by uuid references public.staff(id) on delete set null, received_by_code text, status text not null default 'pending' check (status in ('pending','received','cancelled')), note text, requested_at timestamptz not null default now(), received_at timestamptz, cancelled_at timestamptz, cancelled_by uuid references public.staff(id) on delete set null, cancel_reason text );

create index if not exists pt_status_idx       on public.product_transfer_requests(status);
create index if not exists pt_from_wh_idx      on public.product_transfer_requests(from_warehouse_id);
create index if not exists pt_to_branch_idx    on public.product_transfer_requests(to_branch_id);
create index if not exists pt_product_idx      on public.product_transfer_requests(product_id);
create index if not exists pt_requested_at_idx on public.product_transfer_requests(requested_at desc);

-- 2) CODE GENERATOR — PT-YYYYMMDD-{6 char crockford base32} ---
create or replace function public.gen_product_transfer_code() returns text language plpgsql volatile as $$ declare alphabet text := '0123456789ABCDEFGHJKMNPQRSTVWXYZ'; result text := ''; i int; begin for i in 1..6 loop result := result || substr(alphabet, 1 + floor(random() * 32)::int, 1); end loop; return 'PT-' || to_char(now(), 'YYYYMMDD') || '-' || result; end; $$;
grant execute on function public.gen_product_transfer_code() to anon, authenticated;

-- 3) RPC: REQUEST a product transfer --------------------------
create or replace function public.request_product_transfer(p_product_id uuid, p_from_warehouse_id uuid, p_qty int, p_payment_method text, p_payment_provider text, p_delivery_type text, p_requester_staff_id uuid, p_requester_code text, p_note text) returns text language plpgsql security definer set search_path = public, extensions as $$ declare v_code text; v_item_no text; v_description text; v_dest_warehouse_id uuid; v_dest_branch_id uuid; v_from_branch_id uuid; v_attempts int := 0; begin if not exists (select 1 from staff where id = p_requester_staff_id and (staff_code = p_requester_code or staff_code is null)) then raise exception 'staff code does not match requester'; end if; if p_qty is null or p_qty <= 0 then raise exception 'quantity must be greater than zero'; end if; select item_no, description, warehouse_id, branch_id into v_item_no, v_description, v_dest_warehouse_id, v_dest_branch_id from products where id = p_product_id; if v_item_no is null and v_description is null then raise exception 'product not found'; end if; if v_dest_warehouse_id = p_from_warehouse_id then raise exception 'source and destination warehouse must differ'; end if; select branch_id into v_from_branch_id from branch_warehouses where warehouse_id = p_from_warehouse_id and is_default = true limit 1; if v_from_branch_id is null then select branch_id into v_from_branch_id from branch_warehouses where warehouse_id = p_from_warehouse_id limit 1; end if; loop v_code := public.gen_product_transfer_code(); exit when not exists (select 1 from product_transfer_requests where code = v_code); v_attempts := v_attempts + 1; if v_attempts > 8 then raise exception 'could not generate unique transfer code'; end if; end loop; insert into product_transfer_requests (code, product_id, item_no, description, from_warehouse_id, from_branch_id, to_warehouse_id, to_branch_id, qty_requested, payment_method, payment_provider, delivery_type, requested_by, requested_by_code, note) values (v_code, p_product_id, v_item_no, v_description, p_from_warehouse_id, v_from_branch_id, v_dest_branch_id, v_dest_warehouse_id, p_qty, p_payment_method, p_payment_provider, p_delivery_type, p_requester_staff_id, p_requester_code, p_note); return v_code; end; $$;
grant execute on function public.request_product_transfer(uuid, uuid, int, text, text, text, uuid, text, text) to anon, authenticated;

-- 4) RPC: RECEIVE a product transfer (atomic stock move, STRICT)
--     - locks the row so two clients can't double-receive
--     - requires both source AND destination product rows to exist;
--       raises if either is missing instead of silently skipping.
create or replace function public.receive_product_transfer(p_id uuid, p_receiver_staff_id uuid, p_receiver_code text, p_qty_received int, p_payment_confirmed boolean) returns void language plpgsql security definer set search_path = public, extensions as $$ declare v_req record; v_source_id uuid; v_source_stock int; begin select * into v_req from product_transfer_requests where id = p_id for update; if v_req.id is null then raise exception 'transfer not found'; end if; if v_req.status <> 'pending' then raise exception 'transfer is not pending (current: %)', v_req.status; end if; if not exists (select 1 from staff where id = p_receiver_staff_id and (staff_code = p_receiver_code or staff_code is null)) then raise exception 'receiver staff code does not match'; end if; if p_qty_received is null or p_qty_received <= 0 then raise exception 'received quantity must be greater than zero'; end if; if p_qty_received > v_req.qty_requested then raise exception 'received quantity (%) cannot exceed requested (%)', p_qty_received, v_req.qty_requested; end if; if v_req.product_id is null then raise exception 'destination product row is missing — cannot complete receive'; end if; select id, stock into v_source_id, v_source_stock from products where warehouse_id = v_req.from_warehouse_id and item_no = v_req.item_no limit 1; if v_source_id is null then raise exception 'source warehouse no longer has product % — cannot complete receive', v_req.item_no; end if; if v_source_stock < p_qty_received then raise exception 'source warehouse has only % unit(s) — cannot receive %', v_source_stock, p_qty_received; end if; update products set stock = stock - p_qty_received where id = v_source_id; update products set stock = stock + p_qty_received where id = v_req.product_id; update product_transfer_requests set status = 'received', qty_received = p_qty_received, received_by = p_receiver_staff_id, received_by_code = p_receiver_code, payment_confirmed = coalesce(p_payment_confirmed, false), received_at = now() where id = p_id; end; $$;
grant execute on function public.receive_product_transfer(uuid, uuid, text, int, boolean) to anon, authenticated;

-- 5) RPC: CANCEL a pending transfer ---------------------------
create or replace function public.cancel_product_transfer(p_id uuid, p_by_staff_id uuid, p_reason text) returns void language plpgsql security definer set search_path = public, extensions as $$ declare v_status text; begin select status into v_status from product_transfer_requests where id = p_id for update; if v_status is null then raise exception 'transfer not found'; end if; if v_status <> 'pending' then raise exception 'only pending transfers can be cancelled (current: %)', v_status; end if; update product_transfer_requests set status = 'cancelled', cancelled_at = now(), cancelled_by = p_by_staff_id, cancel_reason = p_reason where id = p_id; end; $$;
grant execute on function public.cancel_product_transfer(uuid, uuid, text) to anon, authenticated;

-- 6) RLS ------------------------------------------------------
alter table public.product_transfer_requests enable row level security;
drop policy if exists "pt_read"  on public.product_transfer_requests;
drop policy if exists "pt_write" on public.product_transfer_requests;
create policy "pt_read"  on public.product_transfer_requests for select using (true);
create policy "pt_write" on public.product_transfer_requests for all using (true) with check (true);

-- 7) Realtime publication -------------------------------------
do $$ begin if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'product_transfer_requests') then execute 'alter publication supabase_realtime add table public.product_transfer_requests'; end if; end $$;
